import type { DemoDataset } from './types'

export const demoData: DemoDataset = {
  organizations: [
    {
      id: 'org-clube',
      name: 'Clube 影像与放映社',
      slug: 'clube',
      description: '一个面向高校影协与艺术策展团队的放映协作助手。',
      inviteCode: 'CLUBE-2026',
      ownerUserId: 'user-lin',
      createdAt: '2026-07-01T09:30:00.000Z',
    },
  ],
  members: [
    {
      id: 'member-1',
      organizationId: 'org-clube',
      userId: 'user-lin',
      name: '林策展',
      role: 'admin',
      joinMethod: 'invite',
      status: 'approved',
    },
    {
      id: 'member-2',
      organizationId: 'org-clube',
      userId: 'user-xu',
      name: '徐放映',
      role: 'staff',
      joinMethod: 'approval',
      status: 'approved',
    },
    {
      id: 'member-3',
      organizationId: 'org-clube',
      userId: 'user-chen',
      name: '陈同学',
      role: 'member',
      joinMethod: 'approval',
      status: 'approved',
    },
    {
      id: 'member-4',
      organizationId: 'org-clube',
      userId: 'user-wang',
      name: '王申请中',
      role: 'member',
      joinMethod: 'approval',
      status: 'pending',
    },
  ],
  screenings: [
    {
      id: 'screening-1',
      organizationId: 'org-clube',
      title: '重庆森林',
      subtitle: 'Wong Kar-wai / 1994 / 城市孤独双章节',
      venue: '文新楼 201',
      startsAt: '2026-07-18T19:00:00.000Z',
      capacity: 80,
      registrations: 63,
      posterUrl:
        'https://coresg-normal.trae.ai/api/ide/v1/text_to_image?prompt=editorial%20film%20club%20poster%2C%20arthouse%20cinema%20screening%20announcement%2C%20warm%20paper%20texture%2C%20subtle%20red%20accents%2C%20minimal%20grid%20layout%2C%20realistic%20print%20design&image_size=portrait_4_3',
      status: 'published',
      curatorNote: '主题聚焦城市关系与时间错位，映后讨论将围绕王家卫的叙事节奏展开。',
    },
    {
      id: 'screening-2',
      organizationId: 'org-clube',
      title: '镜子',
      subtitle: 'Andrei Tarkovsky / 1975 / 记忆、战争与私人影像',
      venue: '艺术学院黑匣子',
      startsAt: '2026-07-24T18:30:00.000Z',
      capacity: 60,
      registrations: 28,
      posterUrl:
        'https://coresg-normal.trae.ai/api/ide/v1/text_to_image?prompt=avant-garde%20cinema%20curation%20poster%2C%20monochrome%20gallery%20layout%2C%20subtle%20grain%2C%20high-end%20editorial%20design%2C%20film%20society%20event%20visual&image_size=portrait_4_3',
      status: 'draft',
      curatorNote: '拟作为“记忆结构”系列第一场，先做内部试映与导赏流程测试。',
    },
    {
      id: 'screening-3',
      organizationId: 'org-clube',
      title: '一一',
      subtitle: 'Edward Yang / 2000 / 家庭、城市与现代性',
      venue: '人文馆报告厅',
      startsAt: '2026-07-30T19:30:00.000Z',
      capacity: 120,
      registrations: 94,
      posterUrl:
        'https://coresg-normal.trae.ai/api/ide/v1/text_to_image?prompt=cinema%20program%20editorial%20poster%2C%20contemporary%20asian%20film%20screening%2C%20minimal%20neutral%20tones%2C%20single%20rust%20red%20accent%2C%20refined%20typography&image_size=portrait_4_3',
      status: 'closed',
      curatorNote: '本场已完成放映与反馈回收，正在导出数据用于复盘。',
    },
  ],
  feedbackEntries: [
    {
      id: 'feedback-1',
      screeningId: 'screening-1',
      rating: 4.8,
      comment: '配合导赏看会更好，片中重复空间的情绪特别明显。',
      createdAt: '2026-07-18T22:00:00.000Z',
    },
    {
      id: 'feedback-2',
      screeningId: 'screening-1',
      rating: 4.5,
      comment: '希望下次增加映后开放提问时间。',
      createdAt: '2026-07-18T22:04:00.000Z',
    },
    {
      id: 'feedback-3',
      screeningId: 'screening-3',
      rating: 4.9,
      comment: '复盘页如果能看评分分布会更直观。',
      createdAt: '2026-07-01T20:24:00.000Z',
    },
  ],
  posts: [
    {
      id: 'post-1',
      organizationId: 'org-clube',
      screeningId: 'screening-1',
      type: 'notice',
      title: '七月策展主题：城市中的旁观者',
      excerpt: '三场放映围绕城市孤独、记忆结构与家庭空间展开。',
      content:
        '本月策展以“城市中的旁观者”为线索，尝试把现代都市里的私人经验与集体观看重新连接起来。',
      author: '林策展',
      publishedAt: '2026-07-10T10:00:00.000Z',
    },
    {
      id: 'post-2',
      organizationId: 'org-clube',
      screeningId: 'screening-3',
      type: 'review',
      title: '《一一》放映后记：如何让复盘不只停留在“感动”',
      excerpt: '从映后问答到匿名反馈，整理出三类最常出现的讨论线索。',
      content:
        '本场反馈显示，观众最集中提到的是家庭结构、儿童视角和城市中产语境，这些都值得在下一场导赏中继续展开。',
      author: '徐放映',
      publishedAt: '2026-07-02T16:30:00.000Z',
    },
  ],
}
